language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # doxygen
  - sudo apt-get install -qq doxygen graphviz

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_doxygen
  - ./check_doc
  #- echo "/** @file */" >> main.cpp; doxygen -g > /dev/null; ( cat Doxyfile ; echo "EXCLUDE=README.md") | doxygen - | egrep "warning"
  # - echo "/*! \\file */" >> main.cpp; doxygen -g > /dev/null; ( cat Doxyfile ; echo "EXCLUDE=README.md") | doxygen -
  #- echo "/*! \\file */" >> main.cpp; doxygen -g > /dev/null; ( cat Doxyfile ; echo "QUIET=YES"; echo "EXCLUDE=README.md" ; echo "WARN_AS_ERROR=YES") | doxygen -
